feat: Added stimulus API for Listbox control using Item Index and Item Name
solitontech/SLL-Drona pull request #81
Opened 2023-08-17 05:41 UTC by kavin1730

Added Stimulus API for listbox control.

![image](https://github.com/solitontech/SLL-Drona/assets/135618969/6310c4f4-dbf0-4af1-abec-5da301d7d5ea)

Test case VIs are added for listbox APIs and tested successfully.

![image](https://github.com/solitontech/SLL-Drona/assets/135618969/0ca81e1d-a79e-4957-a64c-99e18d2664ef)

2023-08-18 07:28 UTC, kavin1730 commented
String API stimulus poly is linked and updated in the listbox branch

Test Report for both string API and listbox stimulus:
![image](https://github.com/solitontech/SLL-Drona/assets/135618969/0171b1e2-ba5a-4dc1-b0e4-248aa472b796)

2023-08-22 05:45 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/ValueSignalByPathArray.vi
Do not close the ctl ref since we need it outside
closing can happen in parent VI

![image](https://github.com/solitontech/SLL-Drona/assets/96038869/a4ec67bf-18c1-4319-8d1c-99965caead49)

2023-08-22 05:48 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SubVIs/MakeItemVisible.vi
add documentation on the logic

2023-08-22 05:50 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByItemName.vi
*Occurrence - spelling

2023-08-22 05:58 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayIndex.vi
- [ ] add short documentation to min logic

2023-08-22 06:04 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayName.vi
- [ ] typedef occurrence cluster

2023-08-22 06:04 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByItemIndex.vi
- [ ] handle error when index > num.elements of list box

2023-08-22 13:15 UTC, Sairam0496 commented on Source/Test/Tests/ListBoxTests/MultiselectListboxStimulus.vi
- [ ]  split into multiple tests - one for each API
- [ ]  check all conditions

2023-08-22 13:20 UTC, Sairam0496 commented on Source/Test/DronaTest.lvlib
- [ ] add Stimulus virtual folder within Listbox Tests

2023-08-23 04:05 UTC, kavin1730 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByItemIndex.vi
Handled with error, since warning gets eliminated when it passes through assert APIs

2023-08-23 12:05 UTC, kavin1730 commented
PR comments are updated:
* Individual tests are created for each stimulus API
* Error handling for different cases
* Added description for specific logic

Test Report for individual APIs:
![image](https://github.com/solitontech/SLL-Drona/assets/135618969/547dc0d0-f2e1-4c52-89a4-0bdcbac5607d)

2023-08-24 05:51 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayIndex.vi
reuse min-max
![image](https://github.com/solitontech/SLL-Drona/assets/96038869/e6a730ea-7d20-4151-8f02-dd8a628734ac)

2023-08-24 06:16 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/typedef/Name&Occuuence.ctl
move to ControlValue.lvlib and reuse for MCLB Stimulus

2023-08-24 06:28 UTC, Sairam0496 requested changes
- [x] do value signalling if only inputs are proper
- [x] throw error if control type is not matching
- [x] Error description can be common "Item not found" (add additional info for specific cases - name, occurrence, index, etc)
- [x] use OpenG Search and reduce the forloop code in Input validation
- [x] rename TestVIs to have "_Tests"
- [x] use setup and teardown subVIs in Tests

2023-08-25 04:26 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByItemName.vi
"Item not found. Item name was not present in specified occurrence" to be changed to "Item not found. Specified occurrence was not found for the Item name"

2023-08-25 04:29 UTC, Sairam0496 commented on Source/APIs/Stimulus/ControlValue/typedef/Name&Occuuence.ctl
- [ ] check spelling of Occurrence in the Ctl name

2023-08-25 04:34 UTC, Sairam0496 requested changes
address the comments

2023-08-25 07:08 UTC, Sairam0496 approved these changes
all good! proceed to merge to main

2023-08-25 07:16 UTC, merged