feat: Add assert APIs to check if the control is in visible/hidden state
solitontech/SLL-Drona pull request #85
Opened 2023-08-23 13:17 UTC by Giri-anandh

Added the Assert to check for the visibility of the given control and added tests for that feature

**Test Report:**
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/0afc6b07-434c-43d8-b6b7-a1aa9250a50e)

2023-08-23 13:31 UTC, kavin1730 commented on Source/Test/Tests/ControlTests/AssertControlDisable_Tests.vi
Need to check, why this test file has been modified.

2023-08-23 13:46 UTC, kavin1730 commented on Source/Test/Tests/ControlTests/AssertControlVisible_Tests.vi
- [ ] Add test for all conditions (different test cases)

2023-08-23 13:49 UTC, kavin1730 requested changes
Added comments on individual files. Update the requested changes.

2023-08-24 05:14 UTC, Giri-anandh commented on Source/Test/Tests/ControlTests/AssertControlDisable_Tests.vi
Added error in for this VI

2023-08-24 05:17 UTC, Giri-anandh commented on Source/Test/Tests/ControlTests/AssertControlInVisible_Tests.vi
Updated the label names
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/09e6f320-3f95-4f99-ba03-dda9d0578efb)

2023-08-24 05:45 UTC, Giri-anandh commented on Source/Test/Tests/ControlTests/AssertControlVisible_Tests.vi
Added additional test cases.
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/42f50fe5-b786-424d-9fb9-0be452969c05)
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/6560aea3-6098-4b97-b5b0-0344b6bb86f4)

2023-08-24 11:35 UTC, kavin1730 commented on Source/Test/Tests/ControlTests/AssertControlInVisible_Tests.vi
- [ ] Use only invisible API to check all conditions

2023-08-24 11:36 UTC, kavin1730 commented on Source/Test/Tests/ControlTests/AssertControlVisible_Tests.vi
- [ ]  Use only visible API to check all conditions

2023-08-24 11:36 UTC, kavin1730 requested changes
Updated the changes requested in test VIs

2023-08-25 04:55 UTC, Giri-anandh commented on Source/Test/Tests/ControlTests/AssertControlVisible_Tests.vi
Updated the code
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/283c22c1-bbad-4c79-86df-80872039e259)

2023-08-25 04:57 UTC, Giri-anandh commented on Source/Test/Tests/ControlTests/AssertControlInVisible_Tests.vi
Updated the code
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/8f6e0204-1847-4003-b867-b185870ad3d4)

2023-08-25 05:02 UTC, kavin1730 approved these changes
All good!

2023-08-25 05:25 UTC, Sairam0496 commented on Source/APIs/Assert/AssertControlVisible/AssertVisible.vi
- [ ] Asserted Value indicator caption can be "Asserted Value (Visible ?)"

2023-08-25 05:25 UTC, Sairam0496 commented on Source/APIs/Assert/AssertControlVisible/AssertInvisible.vi
- [ ] Asserted Value indicator caption can be "Asserted Value (Visible ?)"

2023-08-25 05:34 UTC, Sairam0496 commented on Source/Test/Tests/ControlTests/AssertControlInVisible_Tests.vi
- [ ] check asserted value for both cases

2023-08-25 05:34 UTC, Sairam0496 commented on Source/Test/Tests/ControlTests/AssertControlVisible_Tests.vi
- [ ] check asserted value for both cases

2023-08-25 05:37 UTC, Sairam0496 requested changes
address comments
https://github.com/solitontech/SLL-Drona/pull/85/files#r1305160022
https://github.com/solitontech/SLL-Drona/pull/85/files#r1305160071
https://github.com/solitontech/SLL-Drona/pull/85/files#r1305154396
https://github.com/solitontech/SLL-Drona/pull/85/files#r1305154446

2023-08-25 06:12 UTC, Giri-anandh commented on Source/APIs/Assert/AssertControlVisible/AssertVisible.vi
Changed the label names.

2023-08-25 06:13 UTC, Giri-anandh commented on Source/APIs/Assert/AssertControlVisible/AssertInvisible.vi
Changed the label names.
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/f18a00c5-af75-4517-8f08-3bfbac6852a6)

2023-08-25 06:29 UTC, Giri-anandh commented on Source/Test/Tests/ControlTests/AssertControlInVisible_Tests.vi
Asserted the value 
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/28367e22-bd34-44dc-855d-e279065e61af)

2023-08-25 06:30 UTC, Giri-anandh commented on Source/Test/Tests/ControlTests/AssertControlVisible_Tests.vi
Asserted the value to False
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/128138a9-833e-4003-b0fc-0f999cb5ca12)

2023-08-25 06:49 UTC, Giri-anandh commented on Source/APIs/Assert/AssertControlVisible/AssertVisible.vi
renamed the caption to Asserted Value (Visible ?)

2023-08-25 06:49 UTC, Giri-anandh commented on Source/APIs/Assert/AssertControlVisible/AssertInvisible.vi
renamed the caption to Asserted Value (Visible ?)

2023-08-25 06:51 UTC, Giri-anandh commented on Source/Test/Tests/ControlTests/AssertControlInVisible_Tests.vi
changed the merge error position 
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/f736c71b-b002-4381-a07e-6fdd0a70d6ba)

2023-08-25 06:52 UTC, Giri-anandh commented on Source/Test/Tests/ControlTests/AssertControlVisible_Tests.vi
Changed the merge error position.
![image](https://github.com/solitontech/SLL-Drona/assets/117888154/9b4e60f8-ce58-44aa-bc71-e80325bbb4ed)

2023-08-25 07:12 UTC, Sairam0496 approved these changes
all good! proceed to merge!

2023-08-25 07:15 UTC, merged