feat: added assert API's for listbox control
solitontech/SLL-Drona pull request #86
Opened 2023-08-25 13:00 UTC by kavin1730

Assert API for listbox control:

![image](https://github.com/solitontech/SLL-Drona/assets/135618969/0be2515a-4f0f-4a4b-80bf-2751c0ba5455)
![image](https://github.com/solitontech/SLL-Drona/assets/135618969/349275d4-12f3-4bcb-b61b-56205e571041)

All the Drona tests have been passed.

2023-08-27 12:31 UTC, Sairam0496 commented on Source/APIs/Assert/AssertControlValue/Controls/Listbox/AssertValueByArrayName.vi
Usen OpenG function for multiple indexing
![image](https://github.com/solitontech/SLL-Drona/assets/96038869/5bd95ee5-7473-4fd1-adbc-5aa71a1bceeb)

2023-08-27 12:35 UTC, Sairam0496 commented on Source/APIs/Assert/AssertControlValue/Controls/Listbox/AssertIndexValue.vi
- [ ] check wire bend 
![image](https://github.com/solitontech/SLL-Drona/assets/96038869/4a70f6cb-565f-4f06-b8f5-d39820c20737)

2023-08-27 12:43 UTC, Sairam0496 commented on Source/APIs/Assert/AssertControlValue/Controls/Listbox/AssertAllItems.vi
- [ ] check wire bends 
![image](https://github.com/solitontech/SLL-Drona/assets/96038869/7c0ce76b-5428-4dae-88c6-23b7adb0401b)

2023-08-27 13:08 UTC, Sairam0496 commented on Source/APIs/Assert/Assert[Poly].vi
- [ ] remove space here to make it uniform 
![image](https://github.com/solitontech/SLL-Drona/assets/96038869/89e31da1-c6be-4f1a-b9b9-c51a24ad3092)

2023-08-27 13:17 UTC, Sairam0496 requested changes
address the comments in each file and mark conversations resolved

2023-08-27 13:23 UTC, kavin1730 commented
[like]  Kavin Palanisamy reacted to your message:
________________________________
From: Sairam S ***@***.***>
Sent: Sunday, August 27, 2023 1:17:23 PM
To: solitontech/SLL-Drona ***@***.***>
Cc: Kavin Palanisamy ***@***.***>; Author ***@***.***>
Subject: Re: [solitontech/SLL-Drona] feat: added assert API's for listbox control (PR #86)


@Sairam0496 requested changes on this pull request.

address the comments in each file and mark conversations resolved

—
Reply to this email directly, view it on GitHub<https://github.com/solitontech/SLL-Drona/pull/86#pullrequestreview-1597135519>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BAKWDGPQ3Q2TKT5RVUVI7KDXXNCGHANCNFSM6AAAAAA36PKWFQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-08-28 06:12 UTC, Sairam0496 approved these changes
approved for release v0.5.0

2023-08-28 06:38 UTC, merged