Feat 87 -- list box stimulus
solitontech/SLL-Drona pull request #95
Opened 2023-10-04 12:40 UTC by Giri-anandh

This PR contains the fix which generates error when trying to access disabled items from a list box and testcases are also written to verify the functionality.

2023-10-04 14:25 UTC, kavin1730 commented on Source/Test/Tests/ListBoxTests/Stimulus/LB_NameArray_Tests.vi
- [ ] Remove the breakpoint
![image](https://github.com/solitontech/SLL-Drona/assets/135618969/af774677-a09a-413e-addd-33f7617c1365)

2023-10-04 14:29 UTC, kavin1730 requested changes
Update the case structure directly from search array in all these APIs.

- [x] Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayIndex.vi
- [x] Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayName.vi
- [x] Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByItemIndex.vi
- [x] Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByItemName.vi


Stop searching the for loop, if any one of the item was disabled from the given index, in these VIs

- [x] Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayIndex.vi
- [x] Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayName.vi

2023-10-04 14:47 UTC, Giri-anandh commented on Source/Test/Tests/ListBoxTests/Stimulus/LB_NameArray_Tests.vi
Removed the breakpoint

2023-10-04 17:05 UTC, kavin1730 commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayName.vi
- [ ] Shuffle the array and indexed value in for loop (i.e. search index value from disabled item index)

![image](https://github.com/solitontech/SLL-Drona/assets/135618969/98a80163-3e83-4dc7-bf79-b0117b6abd7a)

2023-10-04 17:08 UTC, kavin1730 requested changes
Update the change mentioned in "Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayName.vi"

2023-10-04 17:29 UTC, Giri-anandh commented on Source/APIs/Stimulus/ControlValue/Controls/Listbox/SetValueByArrayName.vi
swapped the inputs to the for loop

2023-10-05 02:37 UTC, kavin1730 approved these changes
All good.

2023-11-09 05:07 UTC, merged